blog/urls.py
from django.urls import path

from .views import blog_entries, entry_detail

app_name = 'blog'
urlpatterns = [
    path('entries/', blog_entries, name='blog_entries'),
    path('entries/<slug>/', entry_detail, name='entry_detail'),
]

home/urls.py
from django.urls import path

from home.views import home_display, event_display

app_name = 'home'
urlpatterns = [
    path('', home_display, name='home_display'),
    path('event/<slug>/', event_display, name='event_display'),
]

tendance_actu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('download/', include('download.urls')),
    path('contact/', include('contact.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.


class Event(models.Model):
    title = models.CharField(_('Event title'), max_length=60)
    slug = models.SlugField(_('Event slug'), max_length=60, unique=True)
    content = models.TextField(_('Event content'))
    date = models.DateField(_('Event date'))
    published = models.BooleanField(_('Publish event ?'))

    class Meta:
        ordering = ['title']

    def __str__(self):
        return "%s->%s" % (self.title, self.date)

    @classmethod
    def get_events(cls):
        events = Event.objects.filter(published=True)
        return events

    def was_published(self):
        if Event.published:
            return True
    was_published.admin_order_field = 'date'
    was_published.boolean = True
    was_published.short_description = 'Published ?'

home/views.py
from django.shortcuts import render, get_object_or_404

from home.models import Event
from blog.models import Entry

# Create your views here.


def home_display(request):
    entries = Entry.get_top_three_entries()
    events = Event.get_events()
    entries_length = len(entries)
    events_length = len(events)

    return render(request,
                  'home/home_display.html',
                  {'events': events,
                   'entries': entries,
                   'entries_length': entries_length,
                   'events_length': events_length
                   }
                  )


def event_display(request, slug):
    event = get_object_or_404(Event, slug=slug)

    return render(request, 'home/event_display.html', {'event': event})

templates/home/event_display.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load staticfiles %}

{% block title %}
    | {{ event.title }}
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2 class="entry-title">{{ event.title }}</h2>
                <b><i>Date: {{ event.date }}</i></b>
                <hr>
                <p>{{ event.content }}</p><br>
                <div class="item">
                     <div class="social-share">
                        <span>{% trans "Share" %}: </span>
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-google-plus"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/home/home_display.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load staticfiles %}

{% block title %} | Home {% endblock title %}

{% block body_option %} "header-collapse" {% endblock body_option %}

{% block home_option %} current-menu-item {% endblock home_option %}

{% block content %}
    <div class="hero">
        <div class="slider">
            <ul class="slides">
                {% if entries_length != 0 %}
                {% for entry in entries %}
                    <li class="lazy-bg"
                        data-background="{{ entry.image.url }}">
                        <div class="container">
                            <h3 class="slide-subtitle">{{ entry.title }}</h3>
                            <p class="slide-desc">{{ entry.brief_content }}</p>
                            <a href="{% url 'blog:entry_detail' entry.slug %}"
                               class="button cut-corner">
                                {% trans "Read More" %}
                            </a>
                        </div>
                    </li>
                {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>

    <main class="main-content">
        <div class="fullwidth-block testimonial-section">
            <div class="container">
                <div class="quote-slider">
                    <ul class="slides">
                        <li>
                            <blockquote>
                                <p>"
                                    {% blocktrans %}
                                        I wish you all welcome on my site where I
                                        present this this and this...
                                    {% endblocktrans %}
                                    "
                                </p>
                                <cite>Frank Parfait NAMEKONG</cite>
                                <span>{% trans "Founder and CEO" %}</span>
                            </blockquote>
                        </li>

                    </ul>
                </div>
            </div>
        </div> <!-- .testimonial-section -->

        <div class="fullwidth-block upcoming-event-section" data-bg-color="#191919">
            <div class="container">
                <header class="section-header">
                    <h2 class="section-title">{% trans "Upcoming events" %}</h2>
                    <div class="event-nav">
                        <a class="prev" id="event-prev" href="#"><i class="fa fa-caret-left"></i></a>
                        <a class="next" id="event-next" href="#"><i class="fa fa-caret-right"></i></a>
                    </div> <!-- .event-nav -->
                </header> <!-- .section-header -->
                <div class="event-carousel">

                    {% if events_length != 0 %}
                    {% for event in events %}
                        <div class="event">
                            <div class="entry-date">
                                <span class="month">{{ event.date }}</span>
                            </div>
                            <h2 class="entry-title">
                                <a href="{% url 'home:event_display' event.slug %}">{{ event.title }}</a>
                            </h2>
                            <p>{{ event.content }}</p>
                        </div> <!-- .event -->
                    {% endfor %}
                    {% endif %}
                </div> <!-- .event-carousel -->
            </div> <!-- .container -->
        </div> <!-- upcoming-event-section -->
    </main>
{% endblock content %}